version: "3.8"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "1500:1500"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:mypassword@localhost:3306/chat1
    depends_on:
      - db
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://api:1500
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: chat1
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
