version: "3"
services:
  api:
    build: ./backend
    ports:
      - "1500:1500"
    environment:
      - DATABASE_URL=mysql://root:mypassword@localhost:3306/chat
    depends_on:
      - db
  client:
    build: ./frontend
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=chat
    volumes:
      - db_data:/var/lib/mysql
  prisma:
    build: ./backend
    command: ["npx", "prisma", "migrate", "dev"]
    depends_on:
      - db
volumes:
  db_data:

